/**
 * Generate typed GraphQL documents from src/graphql/operations/**\/*.graphql
 * against the vendored, pruned schema/bugsecure.graphql.
 *
 *   node scripts/codegen.ts          # write src/graphql/generated.ts
 *   node scripts/codegen.ts --check  # exit 1 if the committed file is stale (CI)
 *
 * Uses the GraphQL Codegen *core* API with two plugins instead of the codegen
 * CLI: same output, a fraction of the (dev) dependency tree.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { relative } from 'node:path';
import { parseArgs } from 'node:util';

import { codegen } from '@graphql-codegen/core';
import * as typedDocumentNode from '@graphql-codegen/typed-document-node';
import * as typescriptOperations from '@graphql-codegen/typescript-operations';
import { buildSchema, parse, printSchema, validate } from 'graphql';

import {
  GENERATED_PATH,
  loadOperations,
  mergeOperations,
  PRUNED_SCHEMA_PATH,
  REPO_ROOT,
} from './lib/operations.ts';

const HEADER = `/* eslint-disable */
// ---------------------------------------------------------------------------
// GENERATED by scripts/codegen.ts from schema/bugsecure.graphql and
// src/graphql/operations/**/*.graphql — DO NOT EDIT BY HAND. Run \`pnpm codegen\`.
// ---------------------------------------------------------------------------
`;

export const generate = async (): Promise<string> => {
  const schema = buildSchema(readFileSync(PRUNED_SCHEMA_PATH, 'utf8'));
  const operations = loadOperations();

  const errors = validate(schema, mergeOperations(operations));
  if (errors.length > 0) {
    throw new Error(
      `Operations do not validate against schema/bugsecure.graphql — re-run prune-schema:\n${errors
        .map((e) => `  - ${e.message}`)
        .join('\n')}`,
    );
  }

  const output = await codegen({
    filename: GENERATED_PATH,
    schema: parse(printSchema(schema)),
    documents: operations.map((op) => ({ location: op.location, document: op.document })),
    plugins: [{ 'typescript-operations': {} }, { 'typed-document-node': {} }],
    pluginMap: {
      'typescript-operations': typescriptOperations,
      'typed-document-node': typedDocumentNode,
    },
    config: {
      // Documents are sent as strings: no `graphql` runtime dependency.
      documentMode: 'string',
      useTypeImports: true,
      enumType: 'string-literal',
      immutableTypes: true,
      skipTypename: true,
      dedupeFragments: true,
      scalars: {
        DateTime: { input: 'string', output: 'string' },
        JSON: { input: 'unknown', output: 'unknown' },
      },
      strictScalars: true,
    },
  });

  // The plugin imports `DocumentTypeDecoration` (a one-property type) from
  // @graphql-typed-document-node/core. Inline it so neither the build nor the
  // published declaration files depend on that package.
  const IMPORT = "import type { DocumentTypeDecoration } from '@graphql-typed-document-node/core';";
  if (!output.includes(IMPORT))
    throw new Error('codegen output changed shape: DocumentTypeDecoration import not found');
  const inlined = output.replace(
    IMPORT,
    [
      '/** Structural copy of `DocumentTypeDecoration` from @graphql-typed-document-node/core. */',
      'interface DocumentTypeDecoration<TResult, TVariables> {',
      '  __apiType?: (variables: TVariables) => TResult;',
      '}',
    ].join('\n'),
  );

  return `${HEADER}${inlined.trimEnd()}\n`;
};

const main = async (): Promise<void> => {
  const { values } = parseArgs({ options: { check: { type: 'boolean', default: false } } });
  const next = await generate();
  const where = relative(REPO_ROOT, GENERATED_PATH);

  if (values.check) {
    let current = '';
    try {
      current = readFileSync(GENERATED_PATH, 'utf8');
    } catch {
      // missing == stale
    }
    if (current !== next) {
      process.stderr.write(`${where} is out of date. Run: pnpm codegen\n`);
      process.exitCode = 1;
      return;
    }
    process.stderr.write(`${where} is up to date.\n`);
    return;
  }

  writeFileSync(GENERATED_PATH, next);
  process.stderr.write(`Wrote ${where}\n`);
};

await main();
