/**
 * Prune a full BugSecure GraphQL SDL down to what this repository's operations use.
 *
 *   node scripts/prune-schema.ts <path/to/full/schema.graphql> [--out schema/bugsecure.graphql] [--check]
 *
 * Production introspection is disabled and the full schema is not published, so
 * the repository vendors only the slice its own operations reach:
 *
 * - root and object/interface types keep ONLY the fields some operation selects
 *   (plus, for an interface, the fields its kept implementations must carry);
 * - every argument of a kept field is kept (a required argument cannot be
 *   dropped without making the schema lie), and so is the full transitive
 *   closure of the input types those arguments and the operations' variables use;
 * - enums and custom scalars are kept whole when referenced, except the enums in
 *   PUBLISHED_ENUM_VALUES, which keep only the values listed there;
 * - union members are kept only when an operation selects on them;
 * - descriptions are stripped (they document server internals, not the
 *   contract this client depends on), as are non-standard directives.
 *
 * The result is re-validated against every operation before it is written, so a
 * pruned schema that would not type-check the repo's own documents is never
 * produced. Output is sorted and deterministic; `--check` exits non-zero when
 * the file on disk differs (for CI).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import {
  buildSchema,
  type DocumentNode,
  type FieldDefinitionNode,
  getNamedType,
  type GraphQLNamedType,
  type GraphQLSchema,
  type InputValueDefinitionNode,
  isInputObjectType,
  isInterfaceType,
  isObjectType,
  isScalarType,
  isSpecifiedScalarType,
  Kind,
  lexicographicSortSchema,
  parse,
  print,
  printSchema,
  type TypeDefinitionNode,
  TypeInfo,
  validate,
  visit,
  visitWithTypeInfo,
} from 'graphql';

import { loadOperations, mergeOperations, PRUNED_SCHEMA_PATH, REPO_ROOT } from './lib/operations.ts';

const KEPT_DIRECTIVES = new Set(['deprecated', 'specifiedBy', 'oneOf']);

/**
 * Enums published only in part: their other values are internal to BugSecure
 * and never reach this repository (nor the types generated from it). Code that
 * reads one of these enums must handle values outside the list.
 */
const PUBLISHED_ENUM_VALUES: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ['BountyUserRole', new Set(['COMPANY_ADMIN', 'RESEARCHER'])],
]);

export const HEADER = [
  '# ---------------------------------------------------------------------------',
  '# GENERATED by scripts/prune-schema.ts — DO NOT EDIT BY HAND.',
  '#',
  '# The subset of the BugSecure API schema reachable from src/graphql/operations.',
  '# To use a new field: add it to an operation, then re-run',
  '#   pnpm prune-schema <path/to/full/schema.graphql> && pnpm codegen',
  '# ---------------------------------------------------------------------------',
  '',
].join('\n');

interface Usage {
  /** type name → selected field names (object and interface types). */
  readonly fields: Map<string, Set<string>>;
  /** Named types referenced as a whole (inputs, enums, scalars, fragment conditions). */
  readonly types: Set<string>;
}

const collectUsage = (schema: GraphQLSchema, operations: DocumentNode): Usage => {
  const fields = new Map<string, Set<string>>();
  const types = new Set<string>();
  const typeInfo = new TypeInfo(schema);

  const useField = (typeName: string, fieldName: string): void => {
    let set = fields.get(typeName);
    if (!set) {
      set = new Set();
      fields.set(typeName, set);
    }
    set.add(fieldName);
  };

  visit(
    operations,
    visitWithTypeInfo(typeInfo, {
      OperationDefinition(node) {
        const root = schema.getRootType(node.operation);
        if (root) types.add(root.name);
      },
      Field(node) {
        const parent = typeInfo.getParentType();
        const def = typeInfo.getFieldDef();
        if (!parent || !def || node.name.value.startsWith('__')) return;
        useField(parent.name, def.name);
        types.add(getNamedType(def.type).name);
        for (const arg of def.args) types.add(getNamedType(arg.type).name);
      },
      InlineFragment(node) {
        if (node.typeCondition) types.add(node.typeCondition.name.value);
      },
      FragmentDefinition(node) {
        types.add(node.typeCondition.name.value);
      },
      VariableDefinition() {
        const input = typeInfo.getInputType();
        if (input) types.add(getNamedType(input).name);
      },
    }),
  );

  return { fields, types };
};

/** Close over input types (and the enums/scalars they reference) transitively. */
const closeOverInputs = (schema: GraphQLSchema, usage: Usage): void => {
  const queue = [...usage.types];
  while (queue.length > 0) {
    const name = queue.pop();
    if (name === undefined) break;
    const type = schema.getType(name);
    if (!isInputObjectType(type)) continue;
    for (const field of Object.values(type.getFields())) {
      const named = getNamedType(field.type).name;
      if (!usage.types.has(named)) {
        usage.types.add(named);
        queue.push(named);
      }
    }
  }
};

/** Kept interfaces force their selected fields onto every kept implementation. */
const reconcileInterfaces = (schema: GraphQLSchema, usage: Usage): void => {
  for (const [typeName, selected] of usage.fields) {
    const type = schema.getType(typeName);
    if (!isInterfaceType(type)) continue;
    for (const impl of schema.getPossibleTypes(type)) {
      if (!usage.fields.has(impl.name) && !usage.types.has(impl.name)) continue;
      const implFields = usage.fields.get(impl.name) ?? new Set<string>();
      for (const f of selected) implFields.add(f);
      usage.fields.set(impl.name, implFields);
    }
  }
};

const isKept = (type: GraphQLNamedType, usage: Usage): boolean => {
  if (type.name.startsWith('__')) return false;
  if (isScalarType(type) && isSpecifiedScalarType(type)) return false;
  return usage.fields.has(type.name) || usage.types.has(type.name);
};

const stripDirectives = <
  T extends { readonly directives?: readonly { readonly name: { readonly value: string } }[] | undefined },
>(
  node: T,
): T => {
  return { ...node, directives: (node.directives ?? []).filter((d) => KEPT_DIRECTIVES.has(d.name.value)) };
};

const stripInputValue = (node: InputValueDefinitionNode): InputValueDefinitionNode => {
  return { ...stripDirectives(node), description: undefined };
};

const stripField = (node: FieldDefinitionNode): FieldDefinitionNode => {
  return {
    ...stripDirectives(node),
    description: undefined,
    arguments: (node.arguments ?? []).map(stripInputValue),
  };
};

export interface PruneResult {
  readonly sdl: string;
  readonly typeCount: number;
}

export const pruneSchema = (fullSdl: string, operations: DocumentNode): PruneResult => {
  // Round-trip through graphql-js first: merges `extend type` blocks and
  // normalises the SDL so the filter below sees one definition per type.
  const full = buildSchema(fullSdl);
  const opErrors = validate(full, operations);
  if (opErrors.length > 0) {
    throw new Error(
      `Operations do not validate against the FULL schema:\n${opErrors.map((e) => `  - ${e.message}`).join('\n')}`,
    );
  }

  const usage = collectUsage(full, operations);
  closeOverInputs(full, usage);
  reconcileInterfaces(full, usage);

  const normalised = parse(printSchema(full));
  const definitions: TypeDefinitionNode[] = [];

  for (const def of normalised.definitions) {
    if (!('name' in def) || def.name === undefined) continue;
    const type = full.getType(def.name.value);
    if (!type || !isKept(type, usage)) continue;

    switch (def.kind) {
      case Kind.OBJECT_TYPE_DEFINITION:
      case Kind.INTERFACE_TYPE_DEFINITION: {
        const selected = usage.fields.get(def.name.value);
        if (!selected || selected.size === 0) {
          throw new Error(`Type ${def.name.value} is referenced but none of its fields are selected.`);
        }
        const interfaces = (def.interfaces ?? []).filter((i) => {
          const iface = full.getType(i.name.value);
          return iface !== undefined && isKept(iface, usage);
        });
        definitions.push({
          ...stripDirectives(def),
          description: undefined,
          interfaces,
          fields: (def.fields ?? []).filter((f) => selected.has(f.name.value)).map(stripField),
        });
        break;
      }
      case Kind.UNION_TYPE_DEFINITION: {
        const members = (def.types ?? []).filter((t) => {
          const member = full.getType(t.name.value);
          return member !== undefined && isObjectType(member) && usage.fields.has(member.name);
        });
        if (members.length === 0) throw new Error(`Union ${def.name.value} has no selected member types.`);
        definitions.push({ ...stripDirectives(def), description: undefined, types: members });
        break;
      }
      case Kind.INPUT_OBJECT_TYPE_DEFINITION:
        definitions.push({
          ...stripDirectives(def),
          description: undefined,
          fields: (def.fields ?? []).map(stripInputValue),
        });
        break;
      case Kind.ENUM_TYPE_DEFINITION: {
        const published = PUBLISHED_ENUM_VALUES.get(def.name.value);
        const values = (def.values ?? []).filter((v) => published?.has(v.name.value) ?? true);
        if (published && values.length !== published.size) {
          throw new Error(`Enum ${def.name.value} no longer has every value PUBLISHED_ENUM_VALUES lists.`);
        }
        definitions.push({
          ...stripDirectives(def),
          description: undefined,
          values: values.map((v) => ({ ...stripDirectives(v), description: undefined })),
        });
        break;
      }
      case Kind.SCALAR_TYPE_DEFINITION:
        definitions.push({ ...stripDirectives(def), description: undefined });
        break;
      default:
        break;
    }
  }

  const pruned = lexicographicSortSchema(buildSchema(printDocument(definitions)));
  const prunedErrors = validate(pruned, operations);
  if (prunedErrors.length > 0) {
    throw new Error(
      `BUG: operations do not validate against the PRUNED schema:\n${prunedErrors.map((e) => `  - ${e.message}`).join('\n')}`,
    );
  }

  // Sanity: the pruned schema must be a strict subset (no type is invented).
  for (const name of Object.keys(pruned.getTypeMap())) {
    if (!full.getType(name)) throw new Error(`BUG: pruned schema contains unknown type ${name}`);
  }

  const typeCount = Object.values(pruned.getTypeMap()).filter(
    (t) => !t.name.startsWith('__') && !(isScalarType(t) && isSpecifiedScalarType(t)),
  ).length;
  return { sdl: `${HEADER}${printSchema(pruned)}\n`, typeCount };
};

const printDocument = (definitions: readonly TypeDefinitionNode[]): string => {
  return print({ kind: Kind.DOCUMENT, definitions });
};

const main = (): void => {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      out: { type: 'string', default: PRUNED_SCHEMA_PATH },
      check: { type: 'boolean', default: false },
      help: { type: 'boolean', short: 'h', default: false },
    },
  });
  const input = positionals[0];
  if (values.help || input === undefined) {
    process.stderr.write(
      'Usage: node scripts/prune-schema.ts <full-schema.graphql> [--out <file>] [--check]\n',
    );
    process.exitCode = values.help ? 0 : 2;
    return;
  }

  const operations = loadOperations();
  const { sdl, typeCount } = pruneSchema(readFileSync(input, 'utf8'), mergeOperations(operations));
  const out = values.out;
  const where = relative(REPO_ROOT, out);

  if (values.check) {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {
      // missing file == out of date
    }
    if (current !== sdl) {
      process.stderr.write(`${where} is out of date. Run: pnpm prune-schema ${input}\n`);
      process.exitCode = 1;
      return;
    }
    process.stderr.write(`${where} is up to date (${typeCount} types).\n`);
    return;
  }

  writeFileSync(out, sdl);
  process.stderr.write(`Wrote ${where}: ${typeCount} types from ${operations.length} operation file(s).\n`);
};

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
